version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spinner_server
    ports:
      - "5000:5000"
    environment: {}
    restart: unless-stopped